# Jarvis OS mkinitcpio configuration
# This is installed into the ISO's airootfs and used to generate
# the initramfs with TPM, LUKS, and Btrfs support.

MODULES=(btrfs)
BINARIES=()
FILES=()
HOOKS=(
    base
    udev
    autodetect
    microcode
    modconf
    kms
    keyboard
    keymap
    consolefont
    block
    tpm2
    encrypt
    lvm2
    filesystems
    fsck
)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-c -T0)
